# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rekha_pb2 as rekha__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rekha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RekhaStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/rekha.Rekha/CreateCollection',
                request_serializer=rekha__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=rekha__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.DropCollection = channel.unary_unary(
                '/rekha.Rekha/DropCollection',
                request_serializer=rekha__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=rekha__pb2.DropCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/rekha.Rekha/ListCollections',
                request_serializer=rekha__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=rekha__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.CollectionExists = channel.unary_unary(
                '/rekha.Rekha/CollectionExists',
                request_serializer=rekha__pb2.CollectionExistsRequest.SerializeToString,
                response_deserializer=rekha__pb2.CollectionExistsResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/rekha.Rekha/Insert',
                request_serializer=rekha__pb2.InsertRequest.SerializeToString,
                response_deserializer=rekha__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertBatch = channel.stream_unary(
                '/rekha.Rekha/InsertBatch',
                request_serializer=rekha__pb2.InsertRequest.SerializeToString,
                response_deserializer=rekha__pb2.InsertBatchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/rekha.Rekha/Delete',
                request_serializer=rekha__pb2.DeleteRequest.SerializeToString,
                response_deserializer=rekha__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_unary(
                '/rekha.Rekha/Fetch',
                request_serializer=rekha__pb2.FetchRequest.SerializeToString,
                response_deserializer=rekha__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/rekha.Rekha/Search',
                request_serializer=rekha__pb2.SearchRequest.SerializeToString,
                response_deserializer=rekha__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.SearchStream = channel.unary_stream(
                '/rekha.Rekha/SearchStream',
                request_serializer=rekha__pb2.SearchRequest.SerializeToString,
                response_deserializer=rekha__pb2.ScoredPoint.FromString,
                _registered_method=True)
        self.SearchDimRange = channel.unary_unary(
                '/rekha.Rekha/SearchDimRange',
                request_serializer=rekha__pb2.SearchDimRangeRequest.SerializeToString,
                response_deserializer=rekha__pb2.SearchDimRangeResponse.FromString,
                _registered_method=True)
        self.Handshake = channel.unary_unary(
                '/rekha.Rekha/Handshake',
                request_serializer=rekha__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=rekha__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/rekha.Rekha/Heartbeat',
                request_serializer=rekha__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=rekha__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.TransferShard = channel.unary_stream(
                '/rekha.Rekha/TransferShard',
                request_serializer=rekha__pb2.TransferShardRequest.SerializeToString,
                response_deserializer=rekha__pb2.TransferShardChunk.FromString,
                _registered_method=True)
        self.RepairCollection = channel.unary_stream(
                '/rekha.Rekha/RepairCollection',
                request_serializer=rekha__pb2.RepairCollectionRequest.SerializeToString,
                response_deserializer=rekha__pb2.RepairProgress.FromString,
                _registered_method=True)


class RekhaServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertBatch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDimRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RepairCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RekhaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=rekha__pb2.CreateCollectionRequest.FromString,
                    response_serializer=rekha__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=rekha__pb2.DropCollectionRequest.FromString,
                    response_serializer=rekha__pb2.DropCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=rekha__pb2.ListCollectionsRequest.FromString,
                    response_serializer=rekha__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'CollectionExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionExists,
                    request_deserializer=rekha__pb2.CollectionExistsRequest.FromString,
                    response_serializer=rekha__pb2.CollectionExistsResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=rekha__pb2.InsertRequest.FromString,
                    response_serializer=rekha__pb2.InsertResponse.SerializeToString,
            ),
            'InsertBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.InsertBatch,
                    request_deserializer=rekha__pb2.InsertRequest.FromString,
                    response_serializer=rekha__pb2.InsertBatchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=rekha__pb2.DeleteRequest.FromString,
                    response_serializer=rekha__pb2.DeleteResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=rekha__pb2.FetchRequest.FromString,
                    response_serializer=rekha__pb2.FetchResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=rekha__pb2.SearchRequest.FromString,
                    response_serializer=rekha__pb2.SearchResponse.SerializeToString,
            ),
            'SearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchStream,
                    request_deserializer=rekha__pb2.SearchRequest.FromString,
                    response_serializer=rekha__pb2.ScoredPoint.SerializeToString,
            ),
            'SearchDimRange': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDimRange,
                    request_deserializer=rekha__pb2.SearchDimRangeRequest.FromString,
                    response_serializer=rekha__pb2.SearchDimRangeResponse.SerializeToString,
            ),
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=rekha__pb2.HandshakeRequest.FromString,
                    response_serializer=rekha__pb2.HandshakeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=rekha__pb2.HeartbeatRequest.FromString,
                    response_serializer=rekha__pb2.HeartbeatResponse.SerializeToString,
            ),
            'TransferShard': grpc.unary_stream_rpc_method_handler(
                    servicer.TransferShard,
                    request_deserializer=rekha__pb2.TransferShardRequest.FromString,
                    response_serializer=rekha__pb2.TransferShardChunk.SerializeToString,
            ),
            'RepairCollection': grpc.unary_stream_rpc_method_handler(
                    servicer.RepairCollection,
                    request_deserializer=rekha__pb2.RepairCollectionRequest.FromString,
                    response_serializer=rekha__pb2.RepairProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rekha.Rekha', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rekha.Rekha', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Rekha:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/CreateCollection',
            rekha__pb2.CreateCollectionRequest.SerializeToString,
            rekha__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/DropCollection',
            rekha__pb2.DropCollectionRequest.SerializeToString,
            rekha__pb2.DropCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/ListCollections',
            rekha__pb2.ListCollectionsRequest.SerializeToString,
            rekha__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/CollectionExists',
            rekha__pb2.CollectionExistsRequest.SerializeToString,
            rekha__pb2.CollectionExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Insert',
            rekha__pb2.InsertRequest.SerializeToString,
            rekha__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/rekha.Rekha/InsertBatch',
            rekha__pb2.InsertRequest.SerializeToString,
            rekha__pb2.InsertBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Delete',
            rekha__pb2.DeleteRequest.SerializeToString,
            rekha__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Fetch',
            rekha__pb2.FetchRequest.SerializeToString,
            rekha__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Search',
            rekha__pb2.SearchRequest.SerializeToString,
            rekha__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rekha.Rekha/SearchStream',
            rekha__pb2.SearchRequest.SerializeToString,
            rekha__pb2.ScoredPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDimRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/SearchDimRange',
            rekha__pb2.SearchDimRangeRequest.SerializeToString,
            rekha__pb2.SearchDimRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Handshake',
            rekha__pb2.HandshakeRequest.SerializeToString,
            rekha__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rekha.Rekha/Heartbeat',
            rekha__pb2.HeartbeatRequest.SerializeToString,
            rekha__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rekha.Rekha/TransferShard',
            rekha__pb2.TransferShardRequest.SerializeToString,
            rekha__pb2.TransferShardChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RepairCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rekha.Rekha/RepairCollection',
            rekha__pb2.RepairCollectionRequest.SerializeToString,
            rekha__pb2.RepairProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
