use clap::{Parser, Subcommand};
use rekha_client::RekhaClient;

/// Rekha CLI — admin tool for the distributed vector database.
#[derive(Parser)]
#[command(
    name = "rekha",
    about = "Rekha distributed vector database CLI",
    version
)]
struct Cli {
    /// Address of a seed node in the cluster.
    #[arg(short, long, default_value = "localhost:50051")]
    address: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Start a Rekha server node
    Server {
        /// Path to server configuration YAML
        #[arg(short, long)]
        config: String,
    },
    /// Insert a vector with optional payload.
    /// ID is auto-generated by the server.
    Insert {
        #[arg(short, long)]
        payload: Option<String>,
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
    },
    /// Search for nearest neighbors
    Search {
        #[arg(short = 'k', default_value = "10")]
        top_k: usize,
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
    },
    /// Delete vectors by ID
    Delete {
        ids: Vec<u64>,
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
    },
    /// Create a new collection
    CreateCollection {
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
        /// Optional configuration (JSON or YAML string)
        #[arg(long)]
        config: Option<String>,
    },
    /// Drop (delete) a collection
    DropCollection {
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
    },
    /// List all collections
    ListCollections,
    /// Check if a collection exists
    CollectionExists {
        /// Collection name
        #[arg(short, long, default_value = "default")]
        collection: String,
    },
    /// Show cluster info
    Info,
    /// Check cluster health
    Health,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Server { config } => {
            let server = rekha_server::ServerInstance::from_config_file(&config)
                .await
                .map_err(|e| anyhow::anyhow!("Failed to load config: {e}"))?;
            server
                .run()
                .await
                .map_err(|e| anyhow::anyhow!("Server error: {e}"))?;
        }
        _ => {
            let client = RekhaClient::connect(&[cli.address])
                .await
                .map_err(|e| anyhow::anyhow!("Failed to connect: {e}"))?;

            match cli.command {
                Commands::Insert {
                    payload,
                    collection,
                } => {
                    eprintln!("Reading vector from stdin (space-separated floats)...");
                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;
                    let vector: Vec<f32> = input
                        .split_whitespace()
                        .filter_map(|s| s.parse().ok())
                        .collect();

                    if vector.is_empty() {
                        anyhow::bail!("No valid floats provided on stdin");
                    }

                    let actual_id = client
                        .insert(0, vector, &collection, payload.map(|p| p.into_bytes()))
                        .await?;
                    println!("Inserted vector {actual_id}");
                }
                Commands::Search { top_k, collection } => {
                    eprintln!("Reading query vector from stdin (space-separated floats)...");
                    let mut input = String::new();
                    std::io::stdin().read_line(&mut input)?;
                    let query: Vec<f32> = input
                        .split_whitespace()
                        .filter_map(|s| s.parse().ok())
                        .collect();

                    if query.is_empty() {
                        anyhow::bail!("No valid floats provided on stdin");
                    }

                    let results = client.search(query, &collection, top_k).await?;
                    println!("Search results (top {top_k}):");
                    for (i, r) in results.iter().enumerate() {
                        println!("  {}. id={}, score={:.6}", i + 1, r.id, r.score);
                    }
                }
                Commands::Delete { ids, collection } => {
                    let count = client.delete(&collection, &ids).await?;
                    println!("Deleted {count} vectors");
                }
                Commands::Info => {
                    println!("Rekha cluster info:");
                    client.cluster_info().await?;
                }
                Commands::Health => {
                    let _ = client;
                    println!("OK");
                }
                Commands::CreateCollection { collection, config: _ } => {
                    client.create_collection(&collection, 8, 128, 16).await?;
                    println!("Collection '{collection}' created");
                }
                Commands::DropCollection { collection } => {
                    client.drop_collection(&collection).await?;
                    println!("Collection '{collection}' dropped");
                }
                Commands::ListCollections => {
                    let names = client.list_collections().await?;
                    if names.is_empty() {
                        println!("(no collections)");
                    } else {
                        for name in &names {
                            println!("{name}");
                        }
                    }
                }
                Commands::CollectionExists { collection } => {
                    let exists = client.collection_exists(&collection).await?;
                    println!("{}", if exists { "true" } else { "false" });
                }
                Commands::Server { .. } => unreachable!(),
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cli_parse_server() {
        let cli = Cli::try_parse_from(["rekha", "server", "--config", "config.yaml"]).unwrap();
        match cli.command {
            Commands::Server { config } => {
                assert_eq!(config, "config.yaml");
            }
            _ => panic!("expected Server command"),
        }
    }

    #[test]
    fn test_cli_parse_insert() {
        let cli = Cli::try_parse_from(["rekha", "insert"]).unwrap();
        match cli.command {
            Commands::Insert {
                payload,
                collection,
            } => {
                assert!(payload.is_none());
                assert_eq!(collection, "default");
            }
            _ => panic!("expected Insert command"),
        }
    }

    #[test]
    fn test_cli_parse_insert_with_payload() {
        let cli = Cli::try_parse_from(["rekha", "insert", "--payload", "{\"k\":\"v\"}"]).unwrap();
        match cli.command {
            Commands::Insert {
                payload,
                collection,
            } => {
                assert_eq!(payload, Some("{\"k\":\"v\"}".into()));
                assert_eq!(collection, "default");
            }
            _ => panic!("expected Insert command"),
        }
    }

    #[test]
    fn test_cli_parse_insert_with_collection() {
        let cli = Cli::try_parse_from(["rekha", "insert", "-c", "my_collection"]).unwrap();
        match cli.command {
            Commands::Insert {
                payload,
                collection,
            } => {
                assert!(payload.is_none());
                assert_eq!(collection, "my_collection");
            }
            _ => panic!("expected Insert command"),
        }
    }

    #[test]
    fn test_cli_parse_search() {
        let cli = Cli::try_parse_from(["rekha", "search", "-k", "20"]).unwrap();
        match cli.command {
            Commands::Search { top_k, collection } => {
                assert_eq!(top_k, 20);
                assert_eq!(collection, "default");
            }
            _ => panic!("expected Search command"),
        }
    }

    #[test]
    fn test_cli_parse_search_with_collection() {
        let cli =
            Cli::try_parse_from(["rekha", "search", "-k", "5", "--collection", "prod"]).unwrap();
        match cli.command {
            Commands::Search { top_k, collection } => {
                assert_eq!(top_k, 5);
                assert_eq!(collection, "prod");
            }
            _ => panic!("expected Search command"),
        }
    }

    #[test]
    fn test_cli_parse_delete() {
        let cli = Cli::try_parse_from(["rekha", "delete", "1", "2", "3"]).unwrap();
        match cli.command {
            Commands::Delete { ids, collection } => {
                assert_eq!(ids, vec![1, 2, 3]);
                assert_eq!(collection, "default");
            }
            _ => panic!("expected Delete command"),
        }
    }

    #[test]
    fn test_cli_parse_delete_with_collection() {
        let cli = Cli::try_parse_from(["rekha", "delete", "1", "-c", "staging"]).unwrap();
        match cli.command {
            Commands::Delete { ids, collection } => {
                assert_eq!(ids, vec![1]);
                assert_eq!(collection, "staging");
            }
            _ => panic!("expected Delete command"),
        }
    }

    #[test]
    fn test_cli_parse_create_collection() {
        let cli = Cli::try_parse_from(["rekha", "create-collection", "-c", "new_col"]).unwrap();
        match cli.command {
            Commands::CreateCollection { collection, config } => {
                assert_eq!(collection, "new_col");
                assert!(config.is_none());
            }
            _ => panic!("expected CreateCollection command"),
        }
    }

    #[test]
    fn test_cli_parse_create_collection_with_config() {
        let cli = Cli::try_parse_from([
            "rekha",
            "create-collection",
            "-c",
            "new_col",
            "--config",
            "{\"dim\":128}",
        ])
        .unwrap();
        match cli.command {
            Commands::CreateCollection { collection, config } => {
                assert_eq!(collection, "new_col");
                assert_eq!(config, Some("{\"dim\":128}".into()));
            }
            _ => panic!("expected CreateCollection command"),
        }
    }

    #[test]
    fn test_cli_parse_drop_collection() {
        let cli = Cli::try_parse_from(["rekha", "drop-collection", "-c", "old_col"]).unwrap();
        match cli.command {
            Commands::DropCollection { collection } => {
                assert_eq!(collection, "old_col");
            }
            _ => panic!("expected DropCollection command"),
        }
    }

    #[test]
    fn test_cli_parse_list_collections() {
        let cli = Cli::try_parse_from(["rekha", "list-collections"]).unwrap();
        assert!(matches!(cli.command, Commands::ListCollections));
    }

    #[test]
    fn test_cli_parse_collection_exists() {
        let cli = Cli::try_parse_from(["rekha", "collection-exists", "-c", "test_col"]).unwrap();
        match cli.command {
            Commands::CollectionExists { collection } => {
                assert_eq!(collection, "test_col");
            }
            _ => panic!("expected CollectionExists command"),
        }
    }

    #[test]
    fn test_cli_parse_collection_exists_default() {
        let cli = Cli::try_parse_from(["rekha", "collection-exists"]).unwrap();
        match cli.command {
            Commands::CollectionExists { collection } => {
                assert_eq!(collection, "default");
            }
            _ => panic!("expected CollectionExists command"),
        }
    }

    #[test]
    fn test_cli_parse_info() {
        let cli = Cli::try_parse_from(["rekha", "info"]).unwrap();
        assert!(matches!(cli.command, Commands::Info));
    }

    #[test]
    fn test_cli_parse_health() {
        let cli = Cli::try_parse_from(["rekha", "health"]).unwrap();
        assert!(matches!(cli.command, Commands::Health));
    }

    #[test]
    fn test_cli_parse_custom_address() {
        let cli = Cli::try_parse_from(["rekha", "--address", "10.0.0.1:50051", "info"]).unwrap();
        assert_eq!(cli.address, "10.0.0.1:50051");
    }
}
